config/routes.rb
AEA::Application.routes.draw do
  devise_for :users
  root :to => "application#index"
  resources :users
  
  get "games" => "games#index"
  get "games/all_bid" => "games#all_bid", as: 'all_bid_game'
  get "games/:id/request/:money" => "games#req", as: 'request_game'
  get "games/:id/request_bid/:money" => "games#req_bid", as: 'request_bid_game'
  get "games/:id/answer/:des" => "games#answer", as: 'answer_game'
  get "games/:id/result/:des" => "games#result", as: 'result_game'  
  get "games/show_all" => "games#show_all_games", as: 'show_all_game'
  get "games/bid" => "games#bid", as: 'bid_game'
  post "games/bid" => "games#create_bid"
  delete "games/:id" => "games#close", as: "close_game" 
  get "games/:id/visible/:des" => "games#visible", as: "visible_game"
  get "games/my_games" => "games#my_games", as: "my_games" 

end

app/views/layouts/shared/_flash_widget.html.erb
<div id="notice">
  <% if flash[:notice] %>
    <p class="flash-notice">
      <%= flash[:notice] %>
    </p>
  <% end %>
</div>

app/views/layouts/shared/_nav_menu.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="../" class="navbar-brand">AEA</a>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'All PLayers', games_path %>
        </li>
        <% if user_signed_in? %>
          <li>  
            <%= link_to 'Make bid', bid_game_path %>
          </li>
          <li>
            <%= link_to 'See all bids', all_bid_game_path %>
          </li>
          <li>
            <%= link_to 'Manage my bids', my_games_path %>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">  
        <% if user_signed_in? %>
          <li>
            <%= link_to "#{current_user.email} [click to logout]", destroy_user_session_path, :method => :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to 'Login', new_user_session_path %>
          </li>
          <li>
            <%= link_to 'Registration', new_user_registration_path %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/shared/_user_id.html.erb
<% if user_signed_in? %>
  <script type="text/javascript">
      window.currentUser = {
          id : "<%= current_user.id %>"
      }
  </script>   
<% end %>

app/views/layouts/shared/_user_params.html.erb
<% if user_signed_in? %>
  <div id="gamesReguest"></div>
  <script type="text/javascript">
      window.currentUser = {
          id : "<%= current_user.id %>"
      }
  </script>
  <%= subscribe_to "/request/#{current_user.id}" %>    
<% end %>

app/views/layouts/shared/_user_subscribe.html.erb
<% if user_signed_in? %>
  <%= subscribe_to "/request/#{current_user.id}" %>    
<% end %>